Ecommerce/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
	path('', include('ecommerce_app.urls')),
    path('admin/', admin.site.urls),
    ## Social 
 	# path('', include('social.apps.django_app.urls', namespace='social')),
	 ##
    
]+static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)

urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

handler404 = 'ecommerce_app.views.error_404_view'

ecommerce_app/urls.py
from django.urls import path, include #Libreria para utilizar path manejo de urls
from django.conf import settings #Configuracion de nuestro proyecto
from . import views #Importamos nuestras vistas

app_name = 'ecommerce_app' #El nombre de nuestra aplicacion

'''Aqui van nuestras url que apuntan siempre una vista, donde la variable name es la que indica
el nombre por el cual se le asigna a los html. Hay vistas que contienen parametros por ejemplo id
necesarios para identificar que se actualizara o que consulta en especifico se requiere.
'''
urlpatterns = [
 path('', views.principal, name='principal'),
 path('principal/admin', views.principal_admin, name='principal_admin'),
 path('login', views.login, name='login'),
 path('registro/cliente', views.registro_cliente, name="registro_cliente"),	
 path('modificar/cliente/<int:id_cliente>/', views.modificar_cliente, name="modificar_cliente"),
 path('modificar/cliente_normal/', views.modificar_normal, name="modificar_normal"),
 path('cerrar_sesion', views.cerrar_sesion, name='cerrar_sesion'),
 path('registrar/producto', views.registrar_producto, name='registrar_producto'),
 path('agregar/empresa', views.agregar_empresa, name='agregar_empresa'),
 path('carrito', views.carrito, name='carrito'),
 path('agregar/categoria', views.agregar_categoria, name='agregar_categoria'),
 path('modificar/categoria/<int:id_categoria>/', views.modificar_categoria, name='modificar_categoria'),
 path('agregar/genero', views.agregar_genero, name='agregar_genero'),
 path('modificar/genero/<int:id_genero>/', views.modificar_genero, name='modificar_genero'),
 path('agregar/marca', views.agregar_marca, name='agregar_marca'),
 path('modificar/marca/<int:id_marca>/', views.modificar_marca, name='modificar_marca'),
 path('ajax/categoria/subcategorias', views.ajax_categoria_subcategoria, name='ajax_categoria_subcategoria'),
 path('detalle/producto/<int:id_producto>/', views.detalle_producto, name='detalle_producto'),
 path('ajax/subcategoria/marcas', views.ajax_subcategoria_marca, name='ajax_subcategoria_marca'),
 path('modificar/imagen/producto<int:id_producto>/', views.modificar_img_producto, name='modificar_img_producto'),
 path('modificar/producto/<int:id_producto>/', views.modificar_producto, name='modificar_producto'),
 path('delete/prudcto/carrito/<int:id_Pdelete>/', views.Eliminar_producto_carrito, name='Eliminar_producto_carrito'),
 path('ajax/existencia', views.ajax_existencia, name='ajax_existencia'),
 path('registro/lote', views.registrar_lote, name='registrar_lote'),
 path('modificar/lote/<int:id_lote>/', views.modificar_lote, name="modificar_lote"),
 path('email', views.email, name='email'),
 path('perfil/cliente', views.perfil_cliente, name='perfil_cliente'),
 path('modificar/imagen/cliente/<int:id_cliente>/', views.modificar_img_cliente, name='modificar_img_cliente'),
 path('modificar/domicilio/<int:id_domicilio>/', views.modificar_domicilio, name='modificar_domicilio'),
 path('aregar/subcategoria', views.agregar_subcategoria, name='agregar_subcategoria'),
 path('modificar/subcategoria/<int:id_subcategoria>/', views.modificar_subcategoria, name='modificar_subcategoria'),
 path('datos/clientes', views.datos_clientes_admin, name='datos_clientes_admin'),
 path('productos/categorias/<int:id_categoria>/', views.productos_categorias, name='productos_categorias'),
 path('productos/subcategoria/<int:id_categoria>,<int:id_subcategoria>/', views.productos_subcategoria, name='productos_subcategoria'),

 path('productos/facturacion', views.facturacion_producto, name='facturacion_producto'),
 path('productos/facturacion/mes', views.pdf_mes_productos_vendidos, name='pdf_mes_productos_vendidos'),
 path('Detalle/Orden', views.Detalle_Orden, name='Detalle_Orden'),
 path('modificar/empresa/<int:id_empresa>/', views.modificar_empresa, name='modificar_empresa'),
 path('modificar/imagen/empresa/<int:id_empresa>/', views.modificar_img_empresa, name='modificar_img_empresa'),
 path('factura/orden/<int:id>/', views.factura_orden, name='factura_orden'),


]

ecommerce_app/models.py
from django.db import models
from django.contrib.auth.models import User
import sys
import importlib
importlib.reload(sys)
#sys.setdefaultencoding('utf8')

# Create your models here.


class Categoria(models.Model):## Seria bueno agregar campo de img para las categorias, igual para las sub
	"""docstring for Categoria"""
	descripcion_categoria = models.CharField(max_length=50)
	def __str__(self):
		return "{}-{}".format(self.pk,self.descripcion_categoria)

	#si pertenece a Tecnologia, Hogar, Juguetes
class SubCategoria(models.Model):
	"""docstring for Categoria"""
	descripcion_subcategoria = models.CharField(max_length=50)
	categoria = models.ForeignKey(Categoria, on_delete=models.CASCADE)

	def __str__(self):
		return "{}-{}".format(self.pk,self.descripcion_subcategoria)

class Marca(models.Model):
	"""docstring for Marca"""
	descripcion_marca = models.CharField(max_length=50)
	subcategoria = models.ForeignKey(SubCategoria, on_delete=models.CASCADE)

	def __str__(self):
		return "{}".format(self.descripcion_marca,self.subcategoria.descripcion_subcategoria)

#Femenino
#Masculino
#Indefinido 
class Genero(models.Model):#este modelo no solo sirve para el cliente, si no para los productos
	descripcion_genero = models.CharField(max_length=20)
	def __str__(self):
		return "{}-{} " .format(self.pk,self.descripcion_genero)

class MetodoPago(models.Model):
	descripcion_pago = models.CharField(max_length=20)
	def __str__(self):
		return "{}-{} " .format(self.pk,self.descripcion_pago)

class Domicilio(models.Model):
	direccion = models.TextField()
	usuario = models.ForeignKey(User, on_delete=models.CASCADE)
	def __str__(self):
		return "{}-{} " .format(self.pk,self.direccion)

class Empresa(models.Model):
	nombre = models.CharField(max_length=200)
	imagen_logo = models.ImageField(upload_to='Media/logo_empresa/')#upload_to carga un archivo en MEDIA_ROOT creando una carpeta con el nombre entre comillas
	telefono = models.CharField(max_length=50, blank = False, null = False)
	fecha_registro = models.DateField(auto_now_add=True)
	direccion = models.TextField()
	latitude_empresa = models.CharField(max_length=30,null=False)
	longitude_empresa = models.CharField(max_length=30,null=False)
	url_facebook = models.CharField(max_length=100,blank=True,null=True)
	url_instagram = models.CharField(max_length=100,blank=True,null=True)
	correo = models.EmailField()
	descripcion = models.TextField(verbose_name='descripcion_empresa')#Si no se da el nombre detallado, Django lo creará automáticamente usando el nombre del atributo del campo, convirtiendo los guiones bajos en espacios
	
	
	def __str__(self):
		return "{}-{} " .format(self.nombre,self.telefono)

class Producto(models.Model): 
	imagen_producto = models.ImageField(upload_to='Media/productos_empresa/')
	nombre_producto = models.CharField(max_length=200,blank=True,null=True)
	# existencia = models.IntegerField(default=0,blank = True, null = True)
	descripcion_producto = models.CharField(max_length=500,blank=True,null=True)
	modelo = models.CharField(max_length=500,blank=True,null=True)
	fecha_registro = models.DateField(auto_now_add=True,blank=True,null=True)
	precio = models.FloatField(default=0,blank = True, null = True)
	porcentaje_descuento = models.IntegerField(default=0,blank = True, null = True)
	esta_descuento = models.BooleanField(default = False)
	nuevo_producto = models.BooleanField(default = True)
	estado_producto = models.BooleanField(default = True)
	proveedor = models.CharField(max_length=500,blank=True,null=True)
	marca = models.ForeignKey(Marca, on_delete=models.CASCADE)
	categoria_genero = models.ForeignKey(Genero, on_delete=models.CASCADE)#para diferenciar si un producto es para hombre u mujer, esto hara mas facil un filtro u para el buscador


	def __str__(self):
		return "{}-{}" .format(self.pk,self.nombre_producto)
#Cambiar el precio del producto, en caso haya descuento o este en promocion, precio anterior, precio actual
class Carrito(models.Model):
	"""docstring for Carrito"""
	
	cantidad = models.DecimalField(max_digits=10,decimal_places=2, null=True)
	producto =  models.ForeignKey(Producto, on_delete=models.CASCADE)
	usuario = models.ForeignKey(User,on_delete=models.CASCADE, null=True)

	def __str__(self):
		return "{}-{} |{}".format(self.pk,self.cantidad,self.producto.nombre_producto)

class Lote(models.Model):
	"""docstring for lote"""
	fecha_creacion = models.DateField(auto_now_add=True)
	existencia = models.CharField(max_length=50)
	producto =  models.ForeignKey(Producto, on_delete=models.CASCADE)
	def __str__(self):
		return "{}-{} |{}".format(self.pk,self.existencia,self.producto.nombre_producto)
#opcional,  dejar en los datos de la empresa

class Orden(models.Model):
	fecha_compra = models.DateField(auto_now_add=True)
	total = models.DecimalField(max_digits=10,decimal_places=2, null=True)
	metodo_pago = models.ForeignKey(MetodoPago, on_delete=models.CASCADE)
	domicilio = models.ForeignKey(Domicilio, on_delete=models.CASCADE)
	usuario = models.ForeignKey(User, on_delete=models.CASCADE)
	descuento = models.DecimalField(max_digits=10,decimal_places=2, null=True)
	impuesto = models.DecimalField(max_digits=10,decimal_places=2, null=True)
	subtotal = models.DecimalField(max_digits=10,decimal_places=2, null=True)

	def __str__(self):
		return "{}-{} " .format(self.pk,self.total)

class DetalleOrden(models.Model):
	cantidad = models.IntegerField()
	precio = models.DecimalField(max_digits=10,decimal_places=2)
	producto = models.ForeignKey(Producto, on_delete=models.CASCADE)
	orden = models.ForeignKey(Orden, on_delete=models.CASCADE)
	descuento = models.DecimalField(max_digits=10,decimal_places=2, null=True)
	total_producto = models.DecimalField(max_digits=10,decimal_places=2, null=True)

	def __str__(self):
		return "{}-{} |{} " .format(self.pk,self.cantidad,self.precio,self.producto.nombre_producto)


# Modelo cliente
class Cliente(models.Model):
	num_identidad = models.CharField(max_length=20)
	nombres =models.CharField(max_length=100)
	apellidos =models.CharField(max_length=100)
	genero = models.ForeignKey(Genero, on_delete=models.CASCADE)
	numero_telefono = models.CharField(max_length=50)
	fecha_nacimiento = models.DateField(auto_now_add=False)
	fecha_registro = models.DateField(auto_now_add=True)
	correo = models.CharField(max_length=100,blank=True,null=True)
	imagen = models.ImageField(upload_to='Media/imagen_cliente/',blank=True,null=True)
	usuario_cliente = models.ForeignKey(User, on_delete=models.CASCADE)
	def __str__(self):
		return "{}-{} |{}".format(self.nombres,self.apellidos,self.usuario_cliente.username)



#Modelos restantes
#detalle_venta
#carrito
#cliente
#metodo_envio 'empresa, terceros, cliente'
#Marcas,Modelo , Proveedores
#Alertas ''

####cosas geniales ### likes por productos, asi poder mostrarlo en el dashboard, comentarios del producto, productos relacionados
##mapita de la empresa



#Datos de Telegram, trabajar con un chat-id o con group-id
class Telegram(models.Model):
	token = models.CharField(max_length=200)
	groupid = models.CharField(max_length=200)

	def __str__(self):
		return "{}" .format(self.pk)

ecommerce_app/templates/agregar_categoria.html
 {% extends "base_admin.html" %}
 {% block title %}
Easy-buy | Admin
 {% endblock title %}
 {% load static %}
 {% block content %}
 <br>
 <div class="container">
 <section class="content">
 <!-- Formulario de Registro -->
	<div class="card shadow mb-4">
		<aside>
			<!-- ============================ COMPONENT PROFILE  ================================= -->
			<div class="card mb-4">
				<div class="card-header py-3">
					<h5 class="m-0 font-weight-bold text-primary">Registrar Categoría Producto</h5>
				</div>

				<div class="card-body">
					<form role="form" method="post" enctype="multipart/form-data" action="{% url 'ecommerce_app:agregar_categoria' %}" >

						{% csrf_token %}

						{% if errores.administrador %}
						<div class="alert alert-danger alert-dismissible " role="alert">
							<strong>ERROR! </strong>{{errores.administrador}}
						{% endif %}
						</div>

					<div class="form-row">
						<div class="col-md-4">
							<div class="col form-group">
								<label>Categoría Producto:</label>
								<input type="text" class="form-control" id="id_descripcion_categoria" name="descripcion_categoria" placeholder="Descripción Categoría" value="{{ret_data.descripcion_categoria}}">

								{% if errores.descripcion_categoria %}
								<div class="alert alert-danger alert-dismissible " role="alert">
									<strong>ERROR! </strong>{{errores.descripcion_categoria}}
								</div>
								{% endif %}
							</div> <!-- form-group end.// -->
						</div>
					</div>
					
				    <div class="col-sm-4 form-group" style="margin-left: auto; margin-right: auto;">
				        <button type="submit" class="btn btn-primary btn-block" id="guardar"> Guardar  </button>
				    </div>	
					</form>
				</div> <!-- card-body.// -->
			</div> <!-- card .// -->
			<!-- ============================ COMPONENT PROFILE END.// ================================= -->
		</aside>
	
	<!-- Tabla de registros -->
	<div class="card shadow mb-4">
		<div class="card-header py-3">
			<h5 class="m-0 font-weight-bold text-primary">Registros Categoría</h5>
		</div>
		<article class="card-body">
		<div class="table-responsive">
			<table  class="table table-striped table-bordered" id="tablaC"  width="100%" cellspacing="50%">
				<thead>
					<tr>
						<th>Categoría</th>
						<th>Detalles</th>
					</tr>
				</thead>
				<tbody>
					<tr>
					{% for categoria in categorias %}
						<td>{{categoria.descripcion_categoria}}</td>
						<td><button type="button" class="btn btn-secondary" data-toggle="modal" data-target="#id_categoria{{categoria.pk}}">
		                Ver/Editar 
					</tr>
					<!-- Inicio Modal para editar datos-->
					<div class="modal fade" id="id_categoria{{categoria.pk}}">
					  <div class="modal-dialog">
					    <div class="modal-content">

					      <!-- Modal Header -->
					      <div class="modal-header">
					        <h4 class="modal-title">Categoría: {{categoria.descripcion_categoria}}</h4>
					        <button type="button" class="close" data-dismiss="modal">&times;</button>
					      </div>

					      <!-- Modal body -->
					      <div class="modal-body">
					        <form action="{% url 'ecommerce_app:modificar_categoria' categoria.pk %}" method="POST">
			        			{% csrf_token %}
				        		<div class="form-row">
									<div class="col-sm-12 form-group">
										<label>Descripción Categoría:</label>
									  	<input type="text" class="form-control" id="id_descripcion_categoria" name="descripcion_categoria" value="{{categoria.descripcion_categoria}}">
									</div> <!-- form-group end.// -->
								</div> <!-- form-row end.// -->
				        		 <!-- Modal footer -->
				        	    <div class="modal-footer">
						        <button type="button" class="btn btn-danger" data-dismiss="modal">Cerrar</button>
		 						<button type="submit" class="btn btn-secondary">Guardar</button>
						      </div>
					        </form>
					      </div>
					    </div><!-- Final Modal content -->
					  </div><!-- Final Modal dialog -->
					</div><!-- Final Modal -->
					{% endfor %}
				</tbody>
			</table>
		</div>
		</article>
	</div>
	</div>

	
</section>
</div>
{% endblock content %}

{% block js %}
<script type="text/javascript">
$(document).ready(function() {
    $('#tablaC').DataTable({
	  	language: {
            url: '{% static "json/es__es.json" %}'
        }
    });
});
   	function alerta(titulo,icono){
	Swal.fire({ position: 'center', icon: icono, title: titulo, showConfirmButton: false, timer: 2100 })
	history.pushState(null,"","{% url 'ecommerce_app:agregar_categoria' %}");
	}

 	{% if 'ok' in request.GET %}
    	alerta('Datos guardados con éxito','success');
    {% endif %}

    {% if 'ok1' in request.GET %}
    	alerta('Datos actualizados con éxito','success');
    {% endif %}

    {% if 'error1' in request.GET %}
    	alerta('No se ha podido actualizar los datos','error');
    {% endif %}
    
	$('#guardar').click(function(e) {
	   	if($('#id_descripcion_categoria').val() == ''){
	    	Swal.fire('Advertencia','Debe ingresar la descripción de la Categoría','warning')
        	return false;
	    }
	});
</script>
{% endblock js %}

ecommerce_app/templates/carrito.html
 {% extends "base_cliente.html" %}
{% block title %}
Easy-buy | Car_ecommerce
{% endblock title %}
{% load static %}
{% block content %}
<div class="container">
	<br>
	<div class="card-header py-3">
        <h2 class="m-0 font-weight-bold text-primary">Productos agregados</h2>
    </div>
    <hr>
  
<!-- ========================= SECTION CONTENT ========================= -->
<section class="section-content padding-y">
<div class="container">

<div class="row">
    <main class="col-md-9">
<div class="card">

<table class="table table-borderless table-shopping-cart">

<thead class="text-muted">
    {% if carritos != False %}
    
        
    
<tr class="small text-uppercase">
  <th scope="col">Producto</th>
  <th scope="col" width="120">Cantidad | Existencia</th>
  <th scope="col" width="135">Precio</th>
  <th scope="col" class="text-right" width="200"> </th>
</tr>
{% endif %}
</thead>
<tbody>
    {% for car in carritos %}
    {% for exi in existencias  %}
        
        {% ifequal car.producto.pk exi.producto.pk  %}
          
     

        
    
<tr>
    <td>
        <figure class="itemside">
            <div class="aside"><img src="{{car.producto.imagen_producto.url}}" class="img-sm"> <a href="{% url 'ecommerce_app:detalle_producto' car.producto.pk %}">ver </a></div>
            <figcaption class="info">
                <h7 class="title text-black m-2 bg-grey ">{{car.producto.nombre_producto}}</h7>
                <p class="text-muted small">{{car.producto.descripcion_producto}}</p>
            </figcaption>
        </figure>
    </td>
    <td> 
        <div class="price-wrap" align="center"> 
            <var class="price">{{car.cantidad|floatformat:"0"}} | {{exi.existencia}}</var> 
            
        </div> 
    </td>
    <td> 
        <div class="price-wrap"> 
            <var class="price  bg-light ">Lps. {{car.producto.precio}}</var> 
        </div> <!-- price-wrap .// -->
    </td>
    <td class="text-right"> 
    {# <a data-original-title="Save to Wishlist" title="" href="" class="btn btn-light" data-toggle="tooltip"> <i class="fa fa-heart"></i></a>  #}
    <a href="{% url 'ecommerce_app:Eliminar_producto_carrito' car.pk %}" class="btn btn-light text-danger bg-white"> Remover</a>
    </td>
</tr>
{% endifequal %}
    {% endfor %}
{% empty %}
<div class="alert  mt-3">
    <p class="icontext"><i class="icon text-success fa fa-store"></i> Aun no has agregado productos, que esperas!!.</p>
</div>
       
{% endfor %}

</tbody>
</table>

<div class="card-body border-top">
    {% if carrito_vacio == 1  %}

    <a href="{% url 'ecommerce_app:Detalle_Orden' %}" class="btn btn-primary float-md-right" > Ejecutar compra <i class="fa fa-chevron-right"></i> </a>
        
    {% endif %}
    <a href="{% url 'ecommerce_app:principal' %}" class="btn btn-light"> <i class="fa fa-chevron-left"></i> Continuar comprando </a>
</div>  
</div> <!-- card.// target="_blank" -->

<div class="alert alert-success mt-3">
    <p class="icontext"><i class="icon text-success fa fa-truck"></i> Actualmente no se esta contando con el servicio de envios</p>
</div>

    </main> <!---- Estructura para mostrar sudtotal, descuento ect-->
    <aside class="col-md-3">
    
        <div class="card">
            <div class="card-body">
                    <dl class="dlist-align">
                      <dt>Subtotal :</dt>
                      <dd class="text-right">Lps {{e}}</dd>
                    </dl>
                    <dl class="dlist-align">
                      <dt>Descuento :</dt>
                      <dd class="text-right">Lps {{g}}</dd>
                    </dl>
                    <dl class="dlist-align">
                      <dt>Total :</dt>
                      <dd class="text-right  h6"><strong>Lps {{total}}</strong></dd>
                    </dl>
                    <hr>
                    <p class="text-center mb-3">
                       <i class="fa fa-credit-card fa-3x" aria-hidden="true"></i>
                    </p>
                    
            </div> <!-- card-body.// -->
        </div>  <!-- card .// -->
    </aside> <!-- col.// -->
</div>

</div> <!-- container .//  -->
</section>
<!-- ========================= SECTION CONTENT END// ========================= -->
    </div>
<br>
{% endblock content %}

{% block js %}
<script>
    
{% if carrito_vacio == 0 %}
Swal.fire({ position: 'center', icon: 'warning', title: 'No tiene productos agregados en el carrito', showConfirmButton: false, timer: 2000 })
{% endif %}
</script>
{% endblock js %}

ecommerce_app/templates/lista_categorias.html
 {% extends "base_cliente.html" %}
{% block title %}
Easy-buy | Categoías
{% endblock title %}
{% load static %}
{% block content %}

<section class="py-3 bg-light">
  <div class="container">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="{% url 'ecommerce_app:principal' %}">Inicio</a></li>
        <li class="breadcrumb-item active" aria-current="page">Categorías</li>
    </ol>
  </div>
</section>

<section class="section-content padding-y bg">
<div class="container">
 	<div class="row">
 		{% for categoria  in categorias %}
		<div class="col-md-4" style="padding-top: 2%;">
		<!-- ============================ COMPONENT BANNER 1 ================================= -->
			<div class="card-banner rounded-lg" style="height:220px; background-image: url({% static 'images/logo_proyecto.jpg' %});">
			  <article class="card-body caption">
				<h5 class="card-title">{{categoria.descripcion_categoria}}</h5>
				<p>Esta es la descripcion de la categoría {{categoria.pk}}</p>

				<a href="{% url 'ecommerce_app:productos_categoria' categoria.pk %}"  class="btn btn-warning ">Ver</a>
			  </article>
			</div>
		<!-- ======================= COMPONENT BANNER 1  END .// ============================ -->
		</div> <!-- col.// -->
		{% empty %}
		<h1><strong>Lo sentimos, no hay categorías agregadas.</strong></h1>
 		{% endfor %}	

	</div>
</div>
</section>

{% endblock content %}

{% block js %}
{% endblock js %}

ecommerce_app/templates/productos_busqueda.html
{% extends "base_cliente.html" %}
{% block title %}
Easy-buy | Productos
{% endblock title %}
{% load static %}
{% load bootstrap_pagination %}
{% block content %}

<section class="section-content padding-y">
<div class="container">
    <section class="py-3 bg-light">
    <div class=" mb-3">
        <div class="body">
            <ol class="breadcrumb float-left">
               <li class="breadcrumb-item"><a  href="{% url 'ecommerce_app:principal' %}"> Inicio</a></li> 
                {% if request.GET.busqueda %}
                <li class="breadcrumb-item"><a>Resultados de búsqueda para: '{{request.GET.busqueda}}'</a></li>
                {% else %}
                <li class="breadcrumb-item"><a  href="{% url 'ecommerce_app:productos_categorias' categoria.pk %}"> {{categoria.descripcion_categoria}}</a></li>
                {% endif %}
                {% if subcategoria %}
                <li class="breadcrumb-item"><a> {{subcategoria.descripcion_subcategoria}}</a></li>
                {% endif %}
            </ol>
        </div> <!-- card-body .// -->
    </div> <!-- card.// -->
</section>  <br>
<!-- ========================= SECTION INTRO END// ========================= -->

<!-- ========================= SECTION CONTENT ========================= -->
<div class="row">
    <aside class="col-md-3">
     <article class="filter-group">
        <h6 class="title">
            <a href="#" class="dropdown-toggle" data-toggle="collapse" data-target="#collapse_1">    Categorías </a>
        </h6>
        <div class="filter-content collapse show" id="collapse_1" style="">
            <div class="inner">
               <ul class="list-menu">
                {% for categoria in categorias  %}
                <aside class="col-lg col-md-3 flex-lg-grow-0">
                    <nav class="nav-home-aside">
                           <a href="#" class="dropdown-toggle" data-toggle="collapse" data-target="#collapse{{categoria.pk}}">{{categoria.descripcion_categoria}}</a>

                           <div id="collapse{{categoria.pk}}" class="collapse">
                                <a href="{% url 'ecommerce_app:productos_categorias' categoria.pk %}">Todo</a>
                                {% for subcategoria in subcategorias %}
                                {% ifequal subcategoria.categoria.pk categoria.pk  %} 
                                    <li><a href="{% url 'ecommerce_app:productos_subcategoria' categoria.pk subcategoria.pk %}" >{{subcategoria.descripcion_subcategoria}}</a></li>
                                {% endifequal %}
                                {% endfor %}
                            </div>
                           <hr>

                    </nav>
                </aside> <!-- col.// -->
                {% empty %}
                <h3>No hay categorias agregadas</h3>
                {% endfor %}
                </ul>
            </div> <!-- inner.// -->
        </div>
    </article> <!-- filter-group  .// -->

    </aside> <!-- col.// -->
    <main class="col-md-9">

<header class="border-bottom mb-4 pb-3">
        <div class="form-inline">
            <span class="mr-md-auto">{{productos|length}} Productos econtrados </span>
        </div>
</header><!-- sect-heading -->

<div class="row">
    {% for producto in productos  %}
    <div class="col-md-4">
        <figure class="card card-product-grid rounded-lg">
            <div class="img-wrap"> 
                <a  href="{% url 'ecommerce_app:detalle_producto' producto.pk %}" ><img src="{{producto.imagen_producto.url}}"></a>
            </div> <!-- img-wrap.// -->
            <figcaption class="info-wrap">
                <div class="fix-height">
                    <a href="{% url 'ecommerce_app:detalle_producto' producto.pk %}"  class="title">{{producto.nombre_producto}}</a>
                    <div class="price-wrap mt-2">
                        <span class="price">L. {{producto.precio}}0</span>
                    </div> <!-- price-wrap.// -->
                </div>
                <a href="{% url 'ecommerce_app:detalle_producto' producto.pk %}"  class="btn btn-block btn-primary">Ver </a>  
            </figcaption>
        </figure>
    </div> <!-- col.// -->
    {% empty %}
    <h4>Lo sentimos no encontramos lo que busca</h4>
    {% endfor %}
</div> <!-- row end.// -->


<hr>
{% bootstrap_paginate productos range=6 show_first_last="true" extra_pagination_classes="justify-content-left" %}


    </main> <!-- col.// -->

</div>

</div> <!-- container .//  -->
</section>
<!-- ========================= SECTION CONTENT END// ========================= -->
<br>
{% endblock content %}
{% block js %}
<script>

</script>
{% endblock js %}